osx_image: xcode8
language: objective-c
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
script:
  - carthage update --platform iOS --no-use-binaries
  - xcodebuild -project insurance-mobile.xcodeproj -sdk iphonesimulator
